### ISSUE TITLE
Could i use this for my project?

### ISSUE THREAD

**Issue by xlar54** [FrankBoesing/Teensy-reSID#2]
Here's my project:  https://github.com/xlar54/emudore64

It is basically making a 64 emulator the kernel for an operating system.  Low level, but I am wondering how I might incorporate reSID into it.  Do you think this is possible?

**Comment by FrankBoesing** [comment]
Hi, 
reSID might be good for your project. But I'd use the original, not my Arduino-ported version.
If you still want to use my port: Sure, why not.
