### ISSUE TITLE
Digi sound is not clear

### ISSUE THREAD

**Issue by UTilitieeees** [FrankBoesing/Teensy-reSID#3]
I've tested it with "Ghostbusters". The Digi-Speech-Sound "Ghostbusters" (please press the Space Bar) is a little bit "slow" or to "low".

The other games are working good, except "Wizard Of War" (complete destroyed sounds when you are shooting).

**Comment by FrankBoesing** [comment]
Due to the Teensy-Audio-Blocksize and the samplerate,  it is not possible.
